### ISSUE TITLE
...

### ISSUE THREAD

**Issue by zlf766368242** [QualityMinds/cistgcn#1]
There are too many errors in the code

**Comment by emedinac** [comment]
I apologize for the delay in my response. 

During the migration from our server to this repository, a critical file containing one 'layer' file was unfortunately lost. I’ve now updated the repository, not only restoring the missing code but also enhancing the README for greater clarity. Please note that the paths to the model and database will need to be specified in the YAML configuration files.

If you encounter a specific error while running the code, kindly note it down, and I will be happy to review it.
